import 'package:flutter/material.dart';
import '../includes.dart';

EdgeInsets _kColumnPadding(BuildContext context) {
  switch (ResponsiveWidget.getResponsiveType(context)) {
    case ResponsiveType.desktop:
      return const EdgeInsets.only(
        top: 48,
        bottom: 121,
        right: 324,
        left: 324,
      );
    case ResponsiveType.tablet:
      return const EdgeInsets.only(
        top: 32,
        bottom: 121,
        right: 64,
        left: 64,
      );
    case ResponsiveType.mobile:
      return const EdgeInsets.only(
        top: 24,
        bottom: 72,
        right: 23,
        left: 24,
      );
  }
}

TextStyle _titleTextStyle(BuildContext context) {
  return TextStyle(
    fontFamily: 'Inter',
    fontSize: (ResponsiveWidget.isMobileScreen(context) ? 24 : 32.0),
    fontStyle: FontStyle.normal,
    fontWeight: FontWeight.w600,
    height: 1.6,
    color: const Color(0xFF030F2B),
  );
}

TextStyle _subtitleTextStyle(BuildContext context) {
  return TextStyle(
    fontFamily: 'Inter',
    fontSize: (ResponsiveWidget.isMobileScreen(context) ? 20 : 24.0),
    fontStyle: FontStyle.normal,
    fontWeight: FontWeight.w600,
    height: 1.6,
    color: const Color(0xFF030F2B),
  );
}

TextStyle _contentTextStyle(BuildContext context) {
  return TextStyle(
    fontFamily: 'Inter',
    fontSize: (ResponsiveWidget.isMobileScreen(context) ? 14 : 16.0),
    fontStyle: FontStyle.normal,
    fontWeight: FontWeight.w400,
    height: 1.6,
    color: const Color(0xFF030F2B),
  );
}

class TermsPage extends StatefulWidget {
  static const String route = '/terms';
  const TermsPage({
    Key? key,
  }) : super(key: key);

  @override
  State<TermsPage> createState() => _TermsPageState();
}

class _TermsPageState extends State<TermsPage> {
  @override
  void initState() {
    super.initState();
  }

  @override
  void dispose() {
    super.dispose();
  }

  Widget _buildExpandedTextRow(
      BuildContext context, String number, String text) {
    return Row(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          '$number. ',
          style: _contentTextStyle(context),
        ),
        Expanded(
          child: Text(
            text,
            style: _contentTextStyle(context),
          ),
        ),
      ],
    );
  }

  Widget _buildTermsColumn(BuildContext context) {
    return Padding(
      padding: _kColumnPadding(context),
      child: Column(
        mainAxisAlignment: MainAxisAlignment.start,
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            'Terms & Conditions',
            style: _titleTextStyle(context),
          ),
          const SizedBox(height: 40),
          Text(
            'Updated: March 11th, 2022',
            style: _contentTextStyle(context),
          ),
          const SizedBox(height: 22),
          Text(
            'NFT Name is a collection of digital artworks (NFTs) running on the Ethereum network. This website is only an interface allowing participants to purchase digital collectibles. Users are entirely responsible for the safety and management of their own private Ethereum wallets and validating all transactions and contracts generated by this website before approval. Furthermore, as the NFT Name smart contract runs on the Ethereum network, there is no ability to undo, reverse, or restore any transactions.',
            style: _contentTextStyle(context),
          ),
          const SizedBox(height: 22),
          Text(
            'This website and its connected services are provided “as is” and “as available” without warranty of any kind. By using this website you are accepting sole responsibility for any and all transactions involving NFT Name digital collectibles.',
            style: _contentTextStyle(context),
          ),
          const SizedBox(height: 29),
          Text(
            '1. Ownership',
            style: _subtitleTextStyle(context),
          ),
          const SizedBox(height: 8),
          Text(
            'A. You Own the NFT. Each NFT Name is an NFT on the Ethereum blockchain. When you purchase an NFT, you own the underlying NFT Name NFT, the Art, completely. Ownership of the NFT is mediated entirely by the Smart Contract and the Ethereum Network: at no point may we seize, freeze, or otherwise modify the ownership of any NFT Name NFT.',
            style: _contentTextStyle(context),
          ),
          const SizedBox(height: 8),
          Text(
            'B. Personal Use. Subject to your continued compliance with these Terms, Company Name grants you a worldwide, copy, and display the purchased Art, along with any extensions that you choose to create or use, solely for the following purposes: (i) for your own personal, non-commercial use; (ii) as part of a marketplace that permits the purchase and sale of your NFT Name NFT, provided that the marketplace cryptographically verifies each NFT Name NFT owner\'s rights to display the Art for their NFT Name NFT to ensure that only the actual owner can display the Art; or (iii) as part of a third party website or application that permits the inclusion, involvement, or participation of your NFT Name NFT, provided that the website/application cryptographically verifies each NFT Name NFT owner’s rights to display the Art for their NFT Name NFT to ensure that only the actual owner can display the Art, and provided that the Art is no longer visible once the owner of the NFT Name NFT leaves the website/application.',
            style: _contentTextStyle(context),
          ),
          const SizedBox(height: 8),
          Text(
            'C. NFT Name is an encrypted digital asset that recognizes artworks ("artwork(s)") created by Company Name\'s artists ("artist(s)") or partners. Upon your purchase of a NFT Name on this website, you will be granted rights to commercial use as provided in the terms of commercial use on this website.Except as expressly permitted in these terms, you may download the content on this website only for your personal, non-commercial fair use.',
            style: _contentTextStyle(context),
          ),
          const SizedBox(height: 8),
          Text(
            'You understand and accept that you are prohibited from any of the following activities:',
            style: _contentTextStyle(context),
          ),
          const SizedBox(height: 8),
          _buildExpandedTextRow(context, '1',
              'To trademark or apply to trademark the artwork, or otherwise acquire intellectual property rights therein.'),
          _buildExpandedTextRow(context, '2',
              'Use the artwork or NFT Name in connection with images of hatred, violence, other inappropriate behavior, or illegal activities.'),
          _buildExpandedTextRow(context, '3',
              'Upon Company Name marketing and promoting the service, the names and designs of the goods and services related to the service (the "service marks") are protected by the trademark act and fair trade act of applicable jurisdictions according to their registered status or registered use. You may not use the service marks in any way without the prior written consent of Company Name.'),
          const SizedBox(height: 8),
          Text(
            'D. Feedback. You may choose to submit comments, bug reports, ideas or other feedback about the Site, including without limitation about how to improve the Site (collectively, “Feedback”). By submitting any Feedback, you agree that we are free to use such Feedback in any way we choose without additional compensation to you and you hereby grant us a perpetual, irrevocable, nonexclusive, worldwide license to incorporate and use the Feedback for any purpose.',
            style: _contentTextStyle(context),
          ),
          const SizedBox(height: 8),
          Text(
            'E. Unless otherwise provided in these terms, the software, interface, programs, and contents on this website, including but not limited to news, columns, writings, text, pictures, images, music, dance, scripts, signatures, names, stage names, song titles, files, information, data, program structure, interface arrangement, interface design, etc., are owned by Company Name or other rights holders in accordance with the laws. The aforementioned intellectual property rights include but are not limited to trademarks, patents, copyrights, trade secrets and proprietary technology, etc., and may not be used, modified, reproduced, publicly broadcast, altered, distributed, rented, distributed, publicly transmitted, publicly published, restored, decompiled or reverse-compiled by anyone without prior consent. It is your obligation to respect the intellectual property rights, and you shall be liable for any breach thereof and all damages incurred by Company Name or the other rights holders of the intellectual property rights.',
            style: _contentTextStyle(context),
          ),
          const SizedBox(height: 29),
          Text(
            '2. Your Obligations',
            style: _subtitleTextStyle(context),
          ),
          const SizedBox(height: 8),
          Text(
            'You are solely responsible for your own conduct while accessing or using the Site, and for any consequences thereof. You agree to use the Site only for purposes that are legal, proper and in accordance with these Terms and any applicable laws or regulations. By way of example, and not as a limitation, you may not, and may not allow any third party to: (i) send, upload, distribute or disseminate any unlawful, defamatory, harassing, abusive, fraudulent, hateful, violent, obscene, or otherwise objectionable content; (ii) distribute viruses, worms, defects, Trojan horses, corrupted files, hoaxes, or any other items of a destructive or deceptive nature; (iii) impersonate another person; (iv) upload, post, transmit or otherwise make available through the Site any content that infringes the intellectual property or proprietary rights of any party or otherwise violates the legal rights of others; (v) engage in, promote, or encourage illegal activity (including, without limitation, money laundering); (vi) interfere with other users\' use of the Site; (vii) use the Site for any unauthorized commercial purpose; (viii) modify, adapt, translate, or reverse engineer any portion of the Site; (ix) remove any copyright, trademark or other proprietary rights notices contained in or on the Site or any part of it; (x) use any technology to collect information about the Site’s for any unauthorized purpose; (xi) access or use the Site for the purpose of creating a product or service that is competitive with any of our products or services. If you engage in any of the activities prohibited by this Section, we may, at our sole and absolute discretion, without notice to you, and without limiting any of our other rights or remedies at law or in equity, immediately suspend or terminate your user account.',
            style: _contentTextStyle(context),
          ),
          const SizedBox(height: 29),
          Text(
            '3. Fees and Payment',
            style: _subtitleTextStyle(context),
          ),
          const SizedBox(height: 8),
          Text(
            'A. If you elect to purchase a NFT Name NFT through the Site, any financial transactions that you engage in will be conducted solely through the Ethereum network. We will have no insight into or control over these payments or transactions, nor do we have the ability to reverse any transactions.  We will have no liability to you or to any third party for any claims or damages that may arise as a result of any transactions that you engage or any other transactions that you conduct via the Ethereum network.',
            style: _contentTextStyle(context),
          ),
          const SizedBox(height: 8),
          Text(
            'B. Ethereum requires the payment of a transaction fee (a “Gas Fee”) for every transaction that occurs on the Ethereum network. The Gas Fee funds the network of computers that run the decentralized Ethereum network. This means that you will need to pay a Gas Fee for each transaction.',
            style: _contentTextStyle(context),
          ),
          const SizedBox(height: 29),
          Text(
            '4. Disclaimers',
            style: _subtitleTextStyle(context),
          ),
          const SizedBox(height: 8),
          Text(
            'A.  The Platform, Company Name, NFT Name NFT, Finished Items and Special NFTs (if any) are provided on an “as is” and “as available” basis, without warranties of any kind, either express or implied, including, without limitation, implied warranties of merchantability, fitness for a particular purpose, non-infringement, the availability or quality of any NFT Name NFT or Finished Item or Special NFT, or that access to or use of the Platform will be uninterrupted or error free.',
            style: _contentTextStyle(context),
          ),
          const SizedBox(height: 8),
          Text(
            'B.  The Company Name are provided for informational purposes only and are not intended to be a substitute for any type of professional advice, including without limitation legal or financial advice.',
            style: _contentTextStyle(context),
          ),
          const SizedBox(height: 8),
          Text(
            'C.  Company Name has no special relationship with or fiduciary duty to You and Company Name does not in any manner have an ongoing duty to alert You to all potential risks of using or accessing the Platform or in relation to NFT Name NFT(s) or Finished Item or any Transaction(s).',
            style: _contentTextStyle(context),
          ),
          const SizedBox(height: 8),
          Text(
            'D.  Under no circumstances will Company Name be liable to You in any way for:',
            style: _contentTextStyle(context),
          ),
          const SizedBox(height: 8),
          _buildExpandedTextRow(context, '1',
              'Any errors, mistakes, omissions, or inaccuracies relating to Company Name, NFT Name NFT(s), Finished Item, Special NFT, the Platform or any loss or damage of any kind incurred in connection with use of or exposure to any Company Name posted, emailed, accessed, transmitted, or otherwise made available via the Platform, or use or access of the Platform, NFT Name NFT(s), Finished Item or Special NFT;'),
          _buildExpandedTextRow(context, '2',
              'loss or damaged caused by another user’s violation of this Agreement, including any unauthorized access to or use of our servers or other Platform features;'),
          _buildExpandedTextRow(context, '3',
              'any restitution or compensation for loss of profits, revenues, or data;'),
          _buildExpandedTextRow(context, '4',
              'the acts or omissions of any third parties, nor for any damage that You may suffer as a result of Your transactions or any other interaction with any third parties, including third-party providers that provide Wallet services or that store the NFT Name NFT(s) or Finished Item(s).'),
          const SizedBox(height: 8),
          Text(
            'E.  You expressly understand and agree to the following provisions.',
            style: _contentTextStyle(context),
          ),
          const SizedBox(height: 8),
          _buildExpandedTextRow(context, '1',
              'The service may be interrupted or malfunctioned, or may cause inconvenience, loss of data, errors, tampering, or other financial losses to you. You are advised to implement precaution measures when using the service.'),
          _buildExpandedTextRow(context, '2',
              'Company Name shall not be liable for any damages arising out of your use of or inability to use the service, except in cases of Company Name’s intentional infringement or gross negligence.'),
          _buildExpandedTextRow(context, '3',
              'You may not claim to Company Name that any data, goods, services, or other information purchased/obtained through the website does not meet the requirements, expectations, or have defects.'),
          _buildExpandedTextRow(context, '4',
              'Due to the nature of the internet transmission, we cannot guarantee the accuracy and timeliness of all transactions conducted through the website, nor do we guarantee that the service will be available, uninterrupted, safe and secure at all times.'),
          _buildExpandedTextRow(context, '5',
              'No information nor advice you obtained from or through the website, whether obtained in writing or orally, shall constitute a warranty by Company Name.'),
          _buildExpandedTextRow(context, '6',
              'You shall be responsible for any damages and losses arising from any breach of these terms and Company Name shall not be liable for any damages or compensation for losses.'),
          _buildExpandedTextRow(context, '7',
              'You shall be liable for all damages (including but not limited to, the litigation costs and attorneys\' fees) incurred by Company Name or the website from your illegal use of this website or service or breach of these terms.'),
          const SizedBox(height: 8),
          Text(
            'F.  Some jurisdictions do not allow the exclusion of certain warranties and limitations of liability provided in this Agreement. If You are in such a jurisdiction, some of the above limitations and disclaimers may not apply to You. To the extent we may not, as a matter of applicable law, disclaim any implied warranty or limit our liabilities, the scope and duration of such warranty and the extent of our liability will be the minimum permitted by applicable law.',
            style: _contentTextStyle(context),
          ),
          const SizedBox(height: 29),
          Text(
            '5. Limitation of Liability',
            style: _subtitleTextStyle(context),
          ),
          const SizedBox(height: 8),
          Text(
            'A. You understand and agree that in no case shall Company Name, our directors, officers, employees, affiliates, agents, contractors, interns, suppliers, service providers or licensors be liable for any injury, loss, claim, or any direct, indirect, incidental, punitive, special, or consequential damages of any kind, including, without limitation lost profits, lost revenue, lost savings, loss of data, replacement costs, or any similar damages, whether based in contract, tort (including negligence), strict liability or otherwise, arising from your use of any of the service or any products procured using the service, or for any other claim related in any way to your use of the service or any product, including, but not limited to, any errors or omissions in any content, or any loss or damage of any kind incurred as a result of the use of the service or any content (or product) posted, transmitted, or otherwise made available via the service, even if advised of their possibility.',
            style: _contentTextStyle(context),
          ),
          const SizedBox(height: 8),
          Text(
            'B. You acknowledge and agree that we have made the site available to you and entered into these terms in reliance upon the warranty disclaimers and limitations of liability set forth herein. We would not be able to provide the site to you without these limitations.',
            style: _contentTextStyle(context),
          ),
          const SizedBox(height: 29),
          Text(
            '6. Risk Assumption',
            style: _subtitleTextStyle(context),
          ),
          const SizedBox(height: 8),
          Text(
            'A. To the extent that you sell your NFT Name NFT, please be aware that the prices of NFTs are extremely volatile and fluctuations in the prices of other NFTs and impact the price of your NFT Name NFT both positively and negatively.  Given the volatility, NFTs such as NFT Name NFT should not be considered an investment. You assume all risks in that connection.',
            style: _contentTextStyle(context),
          ),
          const SizedBox(height: 8),
          Text(
            'B. Ownership of a NFT Name NFT confers ownership of digital artwork only. Accordingly, no information on this Site (or any other documents mentioned therein) is or may be considered to be advice or an invitation to enter into an agreement for any investment purpose. Further, nothing on this Site qualifies or is intended to be an offering of securities in any jurisdiction nor does it constitute an offer or an invitation to purchase shares, securities or other financial products.  Due to the artistic nature of the project, MAYC has not been registered with or approved by any regulator in any jurisdiction. It remains your sole responsibility to assure that the purchase of the NFT Name NFT and the associated art is in compliance with laws and regulations in your jurisdiction.',
            style: _contentTextStyle(context),
          ),
          const SizedBox(height: 8),
          Text(
            'C. You assume all risks associated with using an Internet-based currency, including, but not limited to, the risk of hardware, software and Internet connections, the risk of malicious software introduction, and the risk that third parties may obtain unauthorized access to information stored within your wallet.',
            style: _contentTextStyle(context),
          ),
          const SizedBox(height: 8),
          Text(
            'D. NFTs, cryptocurrencies and blockchain technology are relatively new and the regulatory landscape is unsettled.  New regulations could negatively impact such technologies impacting the value for your NFT Name NFT. You understand and accept all risk in that regard.',
            style: _contentTextStyle(context),
          ),
          const SizedBox(height: 8),
          Text(
            'E. You assume all responsibility for any adverse effects of disruptions or other issues impacting Ethereum or the Ethereum platform.',
            style: _contentTextStyle(context),
          ),
          const SizedBox(height: 29),
          Text(
            '7. Indemnification',
            style: _subtitleTextStyle(context),
          ),
          const SizedBox(height: 8),
          Text(
            'You agree to hold harmless and indemnify Company Name and its subsidiaries, affiliates, officers, agents, employees, advertisers, licensors, suppliers or partners from and against any claim, liability, loss, damage (actual and consequential) of any kind or nature, suit, judgment, litigation cost, and reasonable attorneys\' fees arising out of or in any way related to (i) your breach of these Terms, (ii) your misuse of the Site, or (iii) your violation of applicable laws, rules or regulations in connection with your access to or use of the Site.',
            style: _contentTextStyle(context),
          ),
          const SizedBox(height: 29),
          Text(
            '8. Changes to the Terms and Conditions',
            style: _subtitleTextStyle(context),
          ),
          const SizedBox(height: 8),
          Text(
            'We may make changes to the Terms at our discretion. Please check these Terms periodically for changes. Any changes to the Terms will apply on the date that they are made, and your continued access to or use after the Terms have been updated will constitute your binding acceptance of the updates. If you do not agree to any revised Terms, you may not access or use the Site.',
            style: _contentTextStyle(context),
          ),
          const SizedBox(height: 29),
          Text(
            '9. Children',
            style: _subtitleTextStyle(context),
          ),
          const SizedBox(height: 8),
          Text(
            'Our Site is not intended for children. You must be at least 18 years old to access this Site or purchase a NFT Name NFT. If you are under 18 years old you are not permitted to use this Site for any reason. By accessing the Site, you represent and warrant that you are at least 18 years of age.',
            style: _contentTextStyle(context),
          ),
          const SizedBox(height: 29),
          Text(
            '10. Dispute Resolution、 Arbitration',
            style: _subtitleTextStyle(context),
          ),
          const SizedBox(height: 8),
          Text(
            'All disputes arising out of or in connection with these Terms, including without limitation your access or use of the Site, or to any products sold or distributed through the Site, will be referred to and finally resolved by arbitration under the rules of the American Arbitration Association. The case will be adjudicated by a single arbitrator and will be administered by the American Arbitration Association in accordance with its applicable rules. Each party will cover its own fees and costs associated with the arbitration proceedings. The place of arbitration will be New York, New York. The award of the arbitrator will be final and binding, and any judgment on the award rendered by the arbitrator may be entered in any court of competent jurisdiction. Notwithstanding the foregoing, we may seek and obtain injunctive relief in any jurisdiction in any court of competent jurisdiction.',
            style: _contentTextStyle(context),
          ),
          const SizedBox(height: 22),
          Text(
            'With respect to any dispute arising out of or related to these terms, including without limitation disputes related to the site or any products sold or distributed through the site, or the smart contracts: (i) you hereby expressly give up your right to have a trial by jury; and (ii) you hereby expressly give up your right to participate as a member of a class of claimants in any lawsuit, including but not limited to class action lawsuits involving any such dispute.',
            style: _contentTextStyle(context),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ListView(
        padding: EdgeInsets.zero,
        children: [
          Container(
            width: ResponsiveWidget.getResponsiveWidth(context),
            height: (ResponsiveWidget.isMobileScreen(context) ? 60 : 84),
            decoration: const BoxDecoration(
              color: Color(0xFFB088ED),
            ),
            child: MouseWidget(
              widget: (bool isOnHover, bool isOnClick) {
                return Image.asset(
                  'assets/images/logo.png',
                  fit: BoxFit.fitHeight,
                );
              },
              onClick: () async {
                Navigator.of(context).popAndPushNamed(NavigationPage.route);
              },
              showUrl: NavigationPage.route,
            ),
          ),
          _buildTermsColumn(context),
          Padding(
            padding: const EdgeInsets.only(bottom: 35),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                const Text(
                  '© 2022 Peter Fan  |',
                  style: TextStyle(
                    fontFamily: 'Inter',
                    fontSize: 14.0,
                    fontStyle: FontStyle.normal,
                    fontWeight: FontWeight.w400,
                    height: 1.4,
                    color: Color(0xFF8F97A3),
                  ),
                ),
                const SizedBox(width: 8),
                MouseWidget(
                  widget: (bool isOnHover, bool isOnClick) {
                    return Text(
                      'Terms & Conditions',
                      style: TextStyle(
                        fontFamily: 'Inter',
                        fontSize: 14.0,
                        fontStyle: FontStyle.normal,
                        fontWeight: FontWeight.w600,
                        height: 1.4,
                        color: const Color(0xFF8F97A3),
                        decoration: isOnHover
                            ? TextDecoration.underline
                            : TextDecoration.none,
                      ),
                    );
                  },
                  onClick: () {
                    Navigator.of(context).popAndPushNamed(TermsPage.route);
                  },
                ),
                const SizedBox(width: 4),
                MouseWidget(
                  widget: (bool isOnHover, bool isOnClick) {
                    return Text(
                      'Privacy Policy',
                      style: TextStyle(
                        fontFamily: 'Inter',
                        fontSize: 14.0,
                        fontStyle: FontStyle.normal,
                        fontWeight: FontWeight.w600,
                        height: 1.4,
                        color: const Color(0xFF8F97A3),
                        decoration: isOnHover
                            ? TextDecoration.underline
                            : TextDecoration.none,
                      ),
                    );
                  },
                  onClick: () {
                    Navigator.of(context).popAndPushNamed(PrivacyPage.route);
                  },
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
